### ISSUE TITLE
Support environment variables in the config

### ISSUE THREAD

**Issue by metafates** [metafates/mangal#103]
### Feature Description

Title says its all

### Solution you would like

```toml
[downloader]
path = "$XDG_CONFIG_HOME/..."
# or any other variable like $MANGA_PATH
```

### Alternatives you have considered

Use env-based configuration rather than file one
