### ISSUE TITLE
version 1.5.2 is broken

### ISSUE THREAD

**Issue by justchokingaround** [metafates/mangal#31]
**Describe the bug**
looking for mangas and reading chapters isn't working properly

**To Reproduce**
1. Search for 'chainsaw man'
Nothing shows up
1. Search for 'tomodachi game'
2. Select first one
`Chapters\n no items`

**Expected behavior**
Should work

**Screenshots**
<img width="629" alt="image" src="https://user-images.githubusercontent.com/44473782/175769375-39fd663a-0c1d-42ce-b05d-41c4bad78e8e.png">
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/44473782/175769435-a40c184c-574f-45bb-a8d9-ce3202b0d9d8.png">

**System**
 - OS: Mac OS
 - Go Version 1.18.3

**Additional context**
This is using the default provider (manganelo) and both pdf and cbz as filetypes

**Comment by metafates** [comment]
Hello! You should update your config file by using `mangal config init -f` (Note that **this will overwrite your existing config**)
This is due to updated scrapers configuration

<img width="618" alt="Screenshot 2022-06-25 at 13 25 48" src="https://user-images.githubusercontent.com/62389790/175769590-0aca0cd4-8f8c-480d-8a50-ac36fc5eca4e.png">

**Comment by metafates** [comment]
Or you can replace your source with that one

```toml
[sources.manganelo]
base = 'https://m.manganelo.com'
chapters_base = 'https://chap.manganelo.com/'
search = 'https://m.manganelo.com/search/story/%s'
manga_anchor = '.search-story-item a.item-title'
manga_title = '.search-story-item a.item-title'
chapter_anchor = 'li.a-h a.chapter-name'
chapter_title = 'li.a-h a.chapter-name'
reader_page = '.container-chapter-reader img'
random_delay_ms = 500
reversed_chapters_order = true
whitespace_escape = "_"
```
